[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

RPC_URL="${RPC_URL}"
PRIVATE_KEY="${PRIVATE_KEY}"
PROCESSING_FEE="${PROCESSING_FEE}"
ETHERSCAN_API_KEY="${ETHERSCAN_API_KEY}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
